import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "@/components/session-provider";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import NavMenu from "@/components/nav-menu";
const inter = Inter({ subsets: ["latin"] });
import toast, { Toaster } from "react-hot-toast";
import { chdir } from "process";
import NavDrawer from "@/components/nav-drawer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" reverseOrder={false} />
        <SessionProvider session={session}>

          {/* sticky/fixed */}
          
        {/* <div className="grid grid-cols-7">
            <div className="block phone:flex tablet:flex laptop:hidden desktop:hidden">
              <NavDrawer />
            </div>
            <aside className="self-start sticky top-0 col-span-1">
              <NavMenu />
            </aside>
            <main className="col-span-6">{children}</main>
          </div> */}

          {/* <div className="grid grid-cols-7">
            <div className="block phone:flex tablet:flex laptop:hidden desktop:hidden">
              <NavDrawer />
            </div>
            <aside className="self-start sticky top-0 col-span-1">
              <NavMenu />
            </aside>
            <main className="col-span-6">{children}</main>
          </div> */}
          {/* <nav className="fixed bottom-[calc(100vh-theme(spacing.16))] left-0 right-0 top-0 bg-blue-200">Nav</nav>
          <div className="flex min-h-screen">
            <div className="block phone:flex tablet:flex laptop:hidden desktop:hidden">
              <NavDrawer />
            </div>
            <div className="sticky top-16 h-[calc(100vh-theme(spacing.16))] w-40 overflow-y-auto">
              <NavMenu />
            </div>
            <main className="mt-16 flex-1 bg-yellow-200">{children}</main>
          </div> */}

          <div className="flex">
              <div className="block phone:flex tablet:flex laptop:hidden desktop:hidden">
                <NavDrawer />
              </div>
              <aside>
                <NavMenu />
              </aside>
              <main className="w-screen h-screen">{children}</main>
            </div>
        </SessionProvider>
      </body>
    </html>
  );
}
